name: CI
on: [push, pull_request]

jobs:
  Build: 
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pull RaLib
        env:
          SSH_KEY_SUBMODULE: ${{secrets.RALIB_KEY}}
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${SSH_KEY_SUBMODULE}"; git submodule update --init --recursive
      - name: Build
        run: ./build.sh
      - name: Run experiments
        run: ./run_evaluation.sh
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results
          retention-days: 5
