name: CI
on: [push, pull_request]

jobs:
  Build: 
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          default: ${{ github.token }}
          ssh-key: ${{secrets.RALIB_KEY}}
          submodules: 'recursive'        
      - name: Build
        run: ./build.sh
      - name: Run experiments
        run: ./run_evaluation.sh
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results
          retention-days: 5
